# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#0066FF"
color_secondary = "#F2F6FF"
body_color = "#fff"
text_color = "#777"
text_dark = "#1E2740"
text_light = "#666666"
border_color = "#E8E8E8"
dark_body_color = "#121212"
dark_text_color = "#cbcbcb"
dark_text_light = "#959595"
dark_text_dark = "#fff"
dark_border_color = "#222"
black = "#000"
white = "#fff"
dark = "#222"
light = "#fdfdfd"

# font variables
# base font size for full website, 
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.25" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_primary = "Open+Sans:wght@400;500;600;700;800" 
font_primary_type = "sans-serif" # [serif/sans-serif]
font_secondary = ""
font_secondary_type = "" # [serif/sans-serif]
font_icon = "Font Awesome 5 Free" # https://fontawesome.com/v5.15/icons/


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.min.css"
[[params.plugins.css]]
link = "plugins/font-awesome/fontawesome.min.css"
[[params.plugins.css]]
link = "plugins/font-awesome/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/solid.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/webfont-loader/webfont-loader-2.min.js"