#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
logo_dark = "images/logo-white.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "120px"
# logo text will only show when logo is missing.
logo_text = "iWriter"
# navbar fixed to top
navbar_fixed = true
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Statichunt"
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true
# Sidebar
sidebar = "true" # sidebar value (true or false)
# copyright
theme_copyright = true
copyright = "Copyright by your company"
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
mainSections = ["blog"]

# theme-mode
theme_switcher = true
theme_default = "system" # available options [light/dark/system]

# Preloader
[preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.


# Instagram feed
[instafeed]
enable = false
access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = ""       # your matomo url
id = ""        # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = ""    # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = ""  # your username

# site verifications
[site_verification]
google = "" # Your verification code
bing = ""   # Your verification code
baidu = ""  # Your verification code


# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["search", "categories", "recent-post", "social"]

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "github"
icon = "fab fa-pinterest" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-youtube" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#"
